title: "Jahleh + Patrick"
description: "The wedding website for Jahleh & Patrick Hooper."
url: "http://jahlehandpatrick.hoopr.io"
source: "../app"
destination: "../public"
gems:
  - "jekyll-sitemap"
markdown: rdiscount
permalink: pretty
