title: "Jahleh + Patrick"
description: "The wedding website for Jahleh & Patrick Hooper."
url: "https://jahlehandpatrick.netlify.com"
source: "../app"
destination: "../public"
gems:
  - "jekyll-sitemap"
markdown: rdiscount
permalink: pretty
